### ISSUE TITLE
Feature request: Hide member list

### ISSUE THREAD

**Issue by c933103** [patrickxchong/hide-discord-sidebar#10]
Without hiding member list, it can only hide the left sidebar not the right sidebar

**Comment by patrickxchong** [comment]
Hi @c933103, sorry for note responding sooner. The right side member list can actually be hidden in Discord itself, all your need to do is to click the Member List icon in the screenshot. 
![image](https://user-images.githubusercontent.com/20418855/130309245-2229cb16-b54d-4f2f-b48a-456c098e5b6f.png)
