### ISSUE TITLE
Feature request: Make channel list temporarily displayable by clicking channel name on top left corner

### ISSUE THREAD

**Issue by c933103** [patrickxchong/hide-discord-sidebar#11]
Aka the bolded channel name next to channel topic

**Comment by patrickxchong** [comment]
@c933103 can you elaborate further on this request? What do you mean by temporarily displayable? With the extension, you don't need to click anything, all you need to do is to hover over the left darker colored bar and the channels list will be revealed. You can see it in action here: https://youtu.be/xmteL4xFL_8?t=4

**Comment by patrickxchong** [comment]
Closed due to inactivity, do reopen and provide more information if the request is still relevant.
