### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by unixfox** [patrickxchong/hide-discord-sidebar#13]
Hello,

Thank you for creating this extension!

Is it possible to add support for Firefox because Firefox support WebExtension too and according to the Firefox Extension Test website your extension has just a few minor fixes to do: https://www.extensiontest.com/test/8091e0d0-0f35-11ec-92b1-0b1cbe167fc4.

**Comment by patrickxchong** [comment]
Hi @unixfox, yes I've been wanting to do that but have not prioritised it (sorry about that). Let me look into it this weekend and see what I can do!

**Comment by patrickxchong** [comment]
Just a status update @unixfox , I managed to fix the compatibility issue, but would like to test this more. Aim to launch this latest by next weekend, will keep you posted!

**Comment by patrickxchong** [comment]
I've submitted the extension to the Mozilla Add-ons store! Will drop another update when it's published 😄

**Comment by patrickxchong** [comment]
Hide Discord Sidebar is published to the Mozilla Addons Store! :tada: You can download it at the link below, do let me know if you encounter any issues with it 
https://addons.mozilla.org/en-US/firefox/addon/hide-discord-sidebar/

**Comment by unixfox** [comment]
Thank you for your work @patrickxchong, the extension works perfectly!

**Comment by patrickxchong** [comment]
Yay I'm glad to hear that! :tada: If it's not too much trouble, would appreciate if you can give the repo a star :blush:
