### ISSUE TITLE
Extension is removed from firefox addons page

### ISSUE THREAD

**Issue by openwick** [patrickxchong/hide-discord-sidebar#14]
Unable to find extension on addons.mozilla.org. Please look into it

**Comment by patrickxchong** [comment]
Hi @openwick , yes I'm aware of that. The Mozilla AddOns store doesn't like one of the libraries I'm using in the extension but to replace it requires quite a bit of a code rewrite that I haven't been able to work on just yet. In the worst case it'll be out by the end of the year when I have more time over the Christmas break, sorry about that!

**Comment by patrickxchong** [comment]
Hey @openwick , I've finally managed to rewrite the code and have submitted it to the Firefox Add-ons store for review, will drop another update here once it's published by them. Apologies for the delay!

**Comment by patrickxchong** [comment]
The extension is back on the Firefox Add-ons store and can be installed at https://addons.mozilla.org/en-US/firefox/addon/hide-discord-sidebar/. Closing this issue, do reach out if you encounter any issues!
