### ISSUE TITLE
No autohiding on Firefox

### ISSUE THREAD

**Issue by gazpachoking** [patrickxchong/hide-discord-sidebar#15]
Just installed this today, so I don't know if it's an issue with a discord update or what, but on latest firefox, autohiding server list or channel list isn't working. The button to manually hid the server list does work though.

**Comment by ampersandru** [comment]
same issue in Chrome - seems discord updated something on their side, so this would need to be updated

**Comment by patrickxchong** [comment]
Hi @gazpachoking and @ampersandru , yes Discord updated their site yesterday and broke the extension. I've fixed that and the updated extensions can be downloaded from the Chrome and Firefox extension stores. Thanks for letting me know!
