### ISSUE TITLE
Singlebox Support?!?!? Please

### ISSUE THREAD

**Issue by jimmaxmim** [patrickxchong/hide-discord-sidebar#17]
Hello there,

I love your extension, it has helped me focus during work hours, but unfortunately I had to transition to [Single box ](https://singlebox.app/)instead of Chrome due to limited screen space.

Can you please get it working on [Single box?](https://singlebox.app/)

Singlebox doesn't support chrome extensions but does have a developer mode:

<img width="792" alt="CleanShot 2022-11-25 at 12 12 23@2x" src="https://user-images.githubusercontent.com/119052104/203983689-c977b56e-642c-40c7-9974-877d3396e0e6.png">

Can we please get this working? @patrickxchong @quanglam2807

**Comment by patrickxchong** [comment]
Sorry for not replying sooner, but I don't have the bandwidth to support Singlebox currently. My apologies :pray:
