### ISSUE TITLE
Hide server button cover discords forum "open in full view" menu

### ISSUE THREAD

**Issue by bokunodev** [patrickxchong/hide-discord-sidebar#19]
as show in the video

https://user-images.githubusercontent.com/54968427/210053178-d034548c-1b90-4f30-9d47-65bb98bcb564.mp4

**Comment by patrickxchong** [comment]
Hello, very sorry for not fixing this issue earlier. I've uploaded v3.3.2 to Firefox which includes the CSS snippet you mentioned above. Firefox has accepted the extension and you should see the issue fixed once the extension is updated on your end. Once again, my humble apologies!
