### ISSUE TITLE
The sidebar stopped collapsing today

### ISSUE THREAD

**Issue by texastoland** [patrickxchong/hide-discord-sidebar#6]

**Comment by patrickxchong** [comment]
Hi @texastoland, I can't seem to replicate the problem on my end. Can you do a hard refresh with CTRL/CMD+SHIFT+R and see if it changes anything? Something that I recently lately is that the extension doesn't work if you navigate from https://discord.com to the webapp, if I start Discord with a in-app link like https://discord.com/channels/@me then it does work. Can you let me know if that changes anything? I've yet looked into a hack to fire the Hide Discord Sidebar script when people navigate from the home page (https://discord.com) into the PWA (https://discord.com/channels/@me).

**Comment by texastoland** [comment]
> Can you do a hard refresh with <kbd>CTRL/CMD+SHIFT+R</kbd>

No change.

> the extension doesn't work if you navigate from [discord.com](https://discord.com) to the webapp

Confirmed for me too.

In my issue the hide servers button works, the sidebar fades, but it doesn't collapse anymore. I'm on the current Edge (Chromium) Dev build 90.0.796.00. Here's my issue in a private window with only your extension enabled:

![2021-02-18 10 31 21](https://user-images.githubusercontent.com/48431/108301474-1060fe80-7170-11eb-98e2-3a1a34db4bfb.gif)

Thanks for getting back to me!

**Comment by patrickxchong** [comment]
Hey @texastoland, thanks for the GIF and the information. I installed Edge Dev on my machine and found out that the browser somehow loaded the extension's CSS before Discord's CSS, hence the extension didn't work. Not sure if it's a feature or bug on their end but I patched it with some !important overrides. I've uploaded the updated package to the Chrome Webstore but will only make it live tomorrow just in case I messed anything up. In the meantime, you can check out this commit for the changes: a7a889ba1345fdd30c6634a31139c547734dd11a. 

Thank you for letting me know about the issue!

**Comment by texastoland** [comment]
Wow excellent sleuthing! It sounds like a bug but I'm not sure how effective sending them feedback would be. I'll verify when it works for me too 👏🏼

**Comment by patrickxchong** [comment]
Hey @texastoland, the updated extension is live. It should automatically update for you in a bit (if it hasn't yet and you want to update it manually I think you can uninstall and reinstall the extension). Let me know how it goes!

**Comment by texastoland** [comment]
Confirmed 🎉
