### ISSUE TITLE
Hide servers too

### ISSUE THREAD

**Issue by jsjoeio** [patrickxchong/hide-discord-sidebar#8]
It would be awesome if you could hide the servers too 😄

(P.S. - thanks for making this!)

**Comment by jsjoeio** [comment]
Nevermind. I just realized this already exists 😅

https://user-images.githubusercontent.com/3806031/119567743-8bcedf00-bd61-11eb-998d-8da2d13b30f1.mov

**Comment by patrickxchong** [comment]
Hey @jsjoeio! Glad you found out that you can hide the servers as well. Just curious, was the extension description/screenshots somehow not clear that it is possible to hide the servers?

**Comment by jsjoeio** [comment]
Well I googled "Hide Discord Sidebar" -> found your extension -> Downloaded without reading what it did and originally thought it could only hide the channel list.

I guess it's because the extension hides the channel list automatically when enabled, but to hide the servers, you have to click a button.

And the button blends in with the UI soooo well that I didn't notice it at first 😅

So really, it's because I was lazy and didn't read the description after installing 😂

**Comment by patrickxchong** [comment]
hahaha all good. The Hide Servers button were intentionally made to match Discord's designs so I'm quite glad you didn't see anything "off". 

As a side note, I'm planning to launch a new version of the extension that allows one to enable/disable the extension and enable/disable autohiding channels, would you be interested to be a beta tester?

**Comment by jsjoeio** [comment]
Sounds awesome. Definitely! Sign me up!

**Comment by patrickxchong** [comment]
Great! Here's a zip file of the new version: [hide-discord-sidebar-v3.zip](https://github.com/patrickxchong/hide-discord-sidebar/files/6555048/hide-discord-sidebar-v3.zip)

Instructions to install the extension (if you need it): https://dev.to/ben/how-to-install-chrome-extensions-manually-from-github-1612

Feel free to share any feedback or issues!

**Comment by jsjoeio** [comment]
Sorry, I was on vacation and just got back. Thanks for the link as well (it's been a while since I've manually installed an extension).

I noticed the previous one was 3.0.0 as well. Are they the same?

So far so good though! I LOVE how focused it makes the chat. Exactly what I wanted 👏

![image](https://user-images.githubusercontent.com/3806031/120370609-a8bb6300-c2c9-11eb-856e-5d8b46413646.png)

**Comment by patrickxchong** [comment]
Hey @jsjoeio I actually launched the new version of the extension over the weekend, so what you install from the Chrome Webstore is pretty much the same thing as the zip file I shared with you (with some improvements). 3.0 adds a popup that you can use to customise the extension behaviour (example below). 

![image](https://user-images.githubusercontent.com/20418855/120468650-050aa980-c3d4-11eb-989d-bc88d33495ae.png)

**Comment by jsjoeio** [comment]
Oh awesome-sauce. Looks great! Curious - why isn't there an "Autohide at all times" for Servers? I would definitely use it if it existed!

**Comment by patrickxchong** [comment]
If you disable autohide for Servers, the extension will remember the state of your servers list. So if you close out your tab with the servers list hidden, the list will still be hidden the next time you open Discord (which is pretty much autohide at all times!)

**Comment by jsjoeio** [comment]
Oh interesting! Gets me what I want - thanks for the tip!

**Comment by patrickxchong** [comment]
You're welcome!
